{% set name = "libcdms" %}
{% set version = "3.1.2" %}
{% set build = 10 %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}
# prioritize nompi variant
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CDAT/libcdms/archive/v{{ version }}.tar.gz
  sha256: 2010ef24f8f8c14a6f997206ec342e6fed9703b81f8641d70bebc992a3855e8c

build:
  number: {{ build }}
  skip: True  # [win]

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `libcdms * mpi_mpich_*` for mpich
  # `libcdms * mpi_*` for any mpi
  # `libcdms * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
    - jasper
    - g2clib
    - libpng
    - libtiff
    - jpeg
    - libdrs
    - libdrs * {{ mpi_prefix }}_*
  run:
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf * {{ mpi_prefix }}_*
    - jasper
    - g2clib
    - libpng
    - libtiff
    - jpeg
    - libdrs * {{ mpi_prefix }}_*

test:
  commands:
    - test -f $PREFIX/lib/libcdms.a

about:
  home: https://github.com/CDAT/libcdms
  license: '3-Clause BSD'
  license_file: 'bsd-3-clause.txt'
  summary: 'Climate Data Management System library'
  description: |
      The Climate Data Management System is an object-oriented data
      management system, specialized for organizing multidimensional,
      gridded data used in climate analysis and simulation.
  dev_url: https://github.com/CDAT/libcdms

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - muryanto1
    - downiec
    - xylar
