travis:
  secure:
    BINSTAR_TOKEN: ja+0LSSLwwRAjfi/oIIDWx59+f/P81hGplGHeYuYUOjB+82aMabXPAhCGZw591a8GEZNveZNfwR2A/iUKKHvfaL4YFz+/e3CmtQYWLAAUTxUUs82qNS6wFhau4bhAiQu3VAVbzzE8vZm2TUVxlenPlDUGwX1bD+UXM8170YAhlfTW8n2GJl1adtFRMa1ZEG7Jj8YHzN2mfxrGtFDoBRnCZuVDq8mKXhnteuBf7hMRCCXNFp/TKptODx0uco6SGoeHNu3Niqh5UN1xB8eCZDGFkAt40ykFa0EWOHlgz2qkeuJWy6Kz1PbpuOInrO+n79SFovA13jht0tN6zoQuLSKs/xZ6dhaco+sDzBMoE+BFACjfM8xeKXxE4JanN6tXS3dNtHW5p6cIE3dXKrIdDdZPGeFDsWRreUWU7yYnboBVhcoWikK6QazcHYr3aIiBSByrzh5NFbwpP7ENj+C022tiVLBb0Xoa6I79h7lCsTyENLf5comfscBzcIdkFePzfaG/fHfSlZzAsDIVZav6wDJYJqhw0Y/8s7lxFmhgL7wLZ5fFtmSjRJwquvMVAb5pyCdSqucMAi2Mp6h3rBJnIADS/M6Odc90318TxKWTw2oRivYKnLTTPgz472O7/iZx3xdgSdfPyWY+YXEinxZewItaZCQ6bdkq+39hFNgYC2hRoY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
